name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Build with latest version of Go
  tools:
    name: Tool
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage
        env:
          EXPORT_RESULT: true

      - name: CodeCov
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          #files: ./coverage.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
              run:

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: dap
          path: out/bin/dap
